artifacts_dir: artifacts
#dns_nameservers:
#  - "144.254.71.184"
clients:
  - name: device1
    id_uri: "sip:lkulf5xjrn_AFFEAFFE0001@90236926.us10.bcld.webex.com"
    registrar_uri: "sip:90236926.us10.bcld.webex.com"
    proxy_uri: "sips:jfk06.hosted-us.bcld.webex.com;lr"
    username_env: WX_SIP_DEVICE1_USER
    password_env: WX_SIP_DEVICE1_PASSWORD
    transport: tls
    enable_video: false
targets: []
